%% D34

%% purpose
% get all the images of the successful picks into one folder and name them
% appropriately

%% prep
% Requires a list of kept picks, called kept_picks.xlsx.  To make it, open
% the spreadsheet generated by the CellCelector software and delete all
% rows of cells that were failed picks (or that don't have images of
% interest associated with them).

% The first three columns of kept_picks.xlsx should be the WellPlate, Well,
% and ID Particle columns (with headers and no empty rows).  
 
% If desired, the fourth column can contain sample names chosen by the user
%(in which case the images will be named after the new naming scheme rather
% than the ID Particle name).  This column header should be called "Final
% Sample Name".

% Note: depending on your version of excel, your WellPlate and Well columns
% may be interpreted as text instead of as numbers. A good indication of
% this is the presence of green triangles in the upper-left-hand corners of
% the cells.  To fix this, select the cells (one column at a time), select 
% the format as Number (Home tab, Number menu), then click on the Text to
% Columns feature (Data tab, Data Tools menu, just click finish when the 
% wizard pops up).

%% inputs
% path where all the images are kept; contains a subfolder for each plate
% and a spreadsheet listing all of the kept picks:
base_path = 'E:\Trial_9-4\Trial_9-4_Colony_lysed\Trial_9-4_colony_lys\';

% the name of the image you want moved and renamed.  If you want to do this
% for multiple images (e.g., the before picking and after picking images),
% run this code multiple times and change the name of the folder you're
% saving to:
image_name = 'Before Picking.tif';

% name the folder all the images will go into:
save_folder = 'colonies_before_picking';


%% execute
% make a folder to save the images in:
mkdir(base_path,save_folder)
save_path = fullfile(base_path,save_folder);
cd(save_path)

% list of the kept picks (and sample names, if desired):
kept_table = importdata(fullfile(base_path,'kept_picks.xlsx'));

for image_count = 1:size(kept_table.data, 1)
    
    plate_folder = num2str(kept_table.data(image_count,1));
    well_folder = num2str(kept_table.data(image_count,2));
    sample_folder = num2str(kept_table.data(image_count,3));
   
    if size(kept_table.textdata,2) == 4
        sample_name = char(strcat(kept_table.textdata(image_count+1,4), '.tif'));
    else
        sample_name = char(strcat(sample_folder, '.tif'));
    end
    
    % identify this image
    image_path = fullfile(base_path, plate_folder, well_folder, sample_folder);
    this_image = fullfile(image_path, image_name);
    % copy the image and rename it
    copyfile(this_image);
    movefile(fullfile(save_path, image_name),fullfile(save_path, sample_name));
    
end
